### ISSUE TITLE
could not find the UM_data

### ISSUE THREAD

**Issue by orangeniux** [mrsergazinov/gluformer#1]
appretiate your work, but there is no file named 'UM_data' in the given link(https://github.com/igfox/multi-output-glucose-forecasting), and perhaps those are the already splited data?

**Comment by mrsergazinov** [comment]
Hey @orangeniux ! Thank you for bringing this up. Indeed, the `UM_data` file refers to the concatenated data from the `processed_cgm_data_*` files in the cited repository. We have updated the repo with the data we have used for training, validation, and testing together with the full data set `UM_data`.

**Comment by orangeniux** [comment]
Its really helpful, thanks a lot!!
